export const BASE_URL = ""
export const BACKEND_URL = "https://sparktech-ecommerce-youtube.onrender.com"
export const PRODUCTS_URL = "/api/products"
export const ORDERS_URL = "/api/orders"
export const USERS_URL = "/api/users"
