export const BASE_URL = ""
export const BACKEND_URL = "http://localhost:5000"
export const PRODUCTS_URL = "/api/products"
export const ORDERS_URL = "/api/orders"
export const USERS_URL = "/api/users"
